### ISSUE TITLE
Error: TypeError: Cannot read properties of null (reading 'discussion')

### ISSUE THREAD

**Issue by mbordash2** [abirismyname/create-discussion#54]
Hello,
Testing this action and keep getting the error in the subject, have you seen this before?

Nothing special configured as you can see below.  I also tried to run with various versions of Node.js and they all return the same error.

```
            - name: Create a new GitHub Discussion
              id: create-discussion
              uses: abirismyname/create-discussion@v1.1.0
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
              with:
                title: Title Goes Here
                body: |
                    Body goes here..
                repository-id: '***'
                category-id: '***'
```

**Comment by franzenr** [comment]
I'm also experiencing the same problem -- haven't been able to figure out a way around it yet

**Comment by mbordash2** [comment]
@franzenr what is your specific use case and does it involve cross-repository discussion?  As far as I can tell, this is a permissions thing...but I haven't figured out a solution yet.  

I am trying to create a new discussion in another repo from where the GHA is running, although within the same organization.

**Comment by mbordash2** [comment]
@franzenr I was able to get this working and it turned out to be really simple but hard to diagnose due to lack of sufficiently helpful error messages.  Ultimately it was the token the GHA was using didn't have permissions to see the repository.

Some things to consider:
- The token must be authorized for the organization if you have SSO enabled.  Just creating a token without proper authorization will fail.
- The new fine grained PAT token must be enabled for your organization.  I ended up just using the classic token as this wasn't enabled to work properly on my org.

I ultimately created a small python program to test this out directly and was able to get better error messages that helped me out.  Below is the code if you'd like to use it to help you diagnose.

```
def create_github_discussion(repo_id, title, body, category_id, token):
    url = "https://api.github.com/graphql"
    headers = {"Authorization": f"Bearer {token}"}
    query = """
        mutation($input: CreateDiscussionInput!) {
          createDiscussion(input: $input) {
            discussion {
              id
              url
            }
          }
        }
    """
    variables = {
        "input": {
            "repositoryId": repo_id,
            "title": title,
            "body": body,
            "categoryId": category_id,
            "clientMutationId": "test"
        }
    }
    response = requests.post(url, json={"query": query, "variables": variables}, headers=headers)
```

**Comment by LCSLITX** [comment]
Just to complement the previous answer, I found an alternate solution.

I experienced this same error and I added the following permissions to respective job: `discussions: write`; `contents: read`.

```yml
  create_discussion:
    needs: [job1]
    runs-on: ubuntu-latest
    # Added permissions
    permissions:
       discussions: write
       contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create a new GitHub Discussion
      id: create-discussion
      uses: abirismyname/create-discussion@v1.2.0
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        title: 'Title'
        body-filepath: 'path/to/file'
        repository-id: ${{ secrets.REPOSITORY_ID }}
        category-id: ${{ secrets.CATEGORY_ID }}
    - name: Print discussion URL
      run: |
        echo discussion-url: ${{steps.create-discussion.outputs.discussion-url}}
```
